=== garyclee/opensaf-hg/config/ValidationConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 sp1 (http://www.altova.com) by nitin (nitin) -->
<!--
 *      -*- OpenSAF  -*-
 *
 * (C) Copyright 2008 The OpenSAF Foundation
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
 * under the GNU Lesser General Public License Version 2.1, February 1999.
 * The complete license can be accessed from the following location:
 * http://opensource.org/licenses/lgpl-license.php
 * See the Copying file included with the OpenSAF distribution for full
 * licensing terms.
 *
 * Author(s): Emerson Network Power
 *
-->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Subba Rao Rama K (Motorola India Private Limited) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ValidationConfig">
		<xs:annotation>
			<xs:documentation>Global type-descriptors for all Valid entities in the System</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="EntityTypeInstance" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Global type-descriptors for all entities in the System.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LocationRange" maxOccurs="8">
								<xs:annotation>
									<xs:documentation>List of possibilities where this  entity can be located.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:attribute name="ParentEntityTypeInstanceName" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>The descriptor name of the parent entity under which this entity can be located.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="LocationRegularExpression" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation>The set of HPI location numbers that this entity can be assigned.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="FRUActivationPolicy">
								<xs:annotation>
									<xs:documentation>The policy for activation of this entity when inserted into  the system.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence minOccurs="0">
										<xs:element name="FruInformation">
											<xs:complexType>
												<xs:attribute name="ProductName" type="xs:string" use="required"/>
												<xs:attribute name="ProductVersion" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Applicable" type="xs:boolean" use="required">
										<xs:annotation>
											<xs:documentation>Must be TRUE for FRUs and FALSE otherwise. If applicable, the 'FRUInformation' MUST be configured.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="FaultDomain" type="faultDomainT" minOccurs="0">
								<xs:annotation>
									<xs:documentation>Fault domain of this entity.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>A unique name for the entity type descriptor.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="HPIEntityType" type="saHPIEntityTypeT" use="required">
							<xs:annotation>
								<xs:documentation>The HPI entity type as defined by SAF HPI</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="IsNode" type="xs:boolean" use="required">
							<xs:annotation>
								<xs:documentation>TRUE if this entity is a processing environment.</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="saHPIEntityTypeT" final="restriction">
		<xs:annotation>
			<xs:documentation>Enumerated Entity Type as defined by SAF HPI</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="SAHPI_ENT_SYSTEM_BOARD"/>
			<xs:enumeration value="SAHPI_ENT_PROCESSOR_MODULE"/>
			<xs:enumeration value="SAHPI_ENT_PROCESSOR"/>
			<xs:enumeration value="SAHPI_ENT_POWER_SUPPLY"/>
			<xs:enumeration value="SAHPI_ENT_PROCESSOR_BOARD"/>
			<xs:enumeration value="SAHPI_ENT_ADVANCEDTCA_CHASSIS"/>
			<xs:enumeration value="SAHPI_ENT_SYSTEM_CHASSIS"/>
			<xs:enumeration value="SAHPI_ENT_RACK"/>
			<xs:enumeration value="SAHPI_ENT_SYSTEM_BLADE"/>
			<xs:enumeration value="SAHPI_ENT_SWITCH_BLADE"/>
			<xs:enumeration value="SAHPI_ENT_IO_BLADE"/>
			<xs:enumeration value="SAHPI_ENT_IO_SUBBOARD"/>
			<xs:enumeration value="SAHPI_ENT_SBC_SUBBOARD"/>
			<xs:enumeration value="SAHPI_ENT_SUBBOARD_CARRIER_BLADE"/>
			<xs:enumeration value="SAHPI_ENT_PHYSICAL_SLOT"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="faultDomainT">
		<xs:annotation>
			<xs:documentation>Enumerated Fault Domain type</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="FAULTDOMAIN_TYPE_SELF"/>
			<xs:enumeration value="FAULTDOMAIN_TYPE_PARENT"/>
			<xs:enumeration value="FAULTDOMAIN_TYPE_GPARENT"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== garyclee/opensaf-hg/config/ValidationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
 *       -*- OpenSAF  -*-
 * 
 *  (C) Copyright 2008 The OpenSAF Foundation 
 * 
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
 *  or FITNESS FOR A PARTICULAR PURPOSE. This file and program are licensed
 *  under the GNU Lesser General Public License Version 2.1, February 1999.
 *  The complete license can be accessed from the following location:
 *  http://opensource.org/licenses/lgpl-license.php 
 *  See the Copying file included with the OpenSAF distribution for full
 *  licensing terms.
 * 
 *  Author(s): Emerson Network Power
 *
-->
<!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<ValidationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ValidationConfig.xsd">
 
	<EntityTypeInstance IsNode="1" Name="CHASSIS" HPIEntityType="SAHPI_ENT_SYSTEM_CHASSIS">
	        <LocationRange ParentEntityTypeInstanceName="ROOT" LocationRegularExpression="1..16"/>
	        <FRUActivationPolicy Applicable="1">
	               <FruInformation ProductVersion="Rev. 01" ProductName="SYS-CONTLR" />
	        </FRUActivationPolicy>
	        <FaultDomain>FAULTDOMAIN_TYPE_SELF</FaultDomain>
        </EntityTypeInstance> 	

	<EntityTypeInstance IsNode="1" Name="CONTROLLER_1" HPIEntityType="SAHPI_ENT_SYSTEM_BOARD">
		<LocationRange ParentEntityTypeInstanceName="CHASSIS" LocationRegularExpression="1..2"/>
		<FRUActivationPolicy Applicable="1">
			<FruInformation ProductVersion="Rev. 01" ProductName="SYS-CONTLR" />
		</FRUActivationPolicy>
		<FaultDomain>FAULTDOMAIN_TYPE_SELF</FaultDomain>
	</EntityTypeInstance>

	<EntityTypeInstance IsNode="1" Name="CONTROLLER_2" HPIEntityType="SAHPI_ENT_SYSTEM_BOARD">
		<LocationRange ParentEntityTypeInstanceName="CHASSIS" LocationRegularExpression="1..2"/>
		<FRUActivationPolicy Applicable="1">
			<FruInformation ProductVersion="Rev. 01" ProductName="SYS-CONTLR" />
		</FRUActivationPolicy>
		<FaultDomain>FAULTDOMAIN_TYPE_SELF</FaultDomain>
	</EntityTypeInstance>
	
	<EntityTypeInstance IsNode="1" Name="PAYLOAD_PC" HPIEntityType="SAHPI_ENT_SYSTEM_BOARD">
			<LocationRange ParentEntityTypeInstanceName="CHASSIS" LocationRegularExpression="3..16"/>
			<FRUActivationPolicy Applicable="1">
				<FruInformation ProductVersion="Rev. 01" ProductName="PAYLOAD-PC" />
			</FRUActivationPolicy>
			<FaultDomain>FAULTDOMAIN_TYPE_SELF</FaultDomain>
	</EntityTypeInstance>

  
</ValidationConfig>
